### ISSUE TITLE
Add more styling to hints

### ISSUE THREAD

**Issue by Dozorengel** [robertgr991/php-parameter-hint#1]
I'm used to dimmer font and background color, for example how it is implemented in a similar extension [IntelliJ Parameter Hints](https://github.com/bzrncev/intellij-parameter-hints).
Indeed, this extension is more powerful than the other one above. It provides more hints, for example in nested structures, where they are also more properly indented. It would be great if it was even more customizable.
![Untitled](https://user-images.githubusercontent.com/40327659/76732706-48aad080-679a-11ea-8305-77499b45d4c9.png)

**Comment by robertgr991** [comment]
Have you tried changing the colors in "settings.json" like this? 
![image](https://user-images.githubusercontent.com/36689800/76741355-18523a80-6778-11ea-88c1-9b871b0b40cd.png)

The colors above will make the hints look like the default ones from that extension. Let me know if you have further problems.

**Comment by Dozorengel** [comment]
Oh, how could I miss that? I haven't even realized as those options are not in the Settings (UI) list. Next time I'll be reading the documentation more thoroughly. Thx a lot!
