### ISSUE TITLE
Background opacity and padding

### ISSUE THREAD

**Issue by muametgrooby** [robertgr991/php-parameter-hint#2]
Hello is there a way i can set background opacity and padding? There's too much unnecessary padding

**Comment by robertgr991** [comment]
Hello,

Right know it's not possible to set the background opacity and padding, but it can be done. I will try to add this options these days.
In the meantime, you can try and lower the left and right margin of the hints, maybe it can help.
It's possible to change it from the settings:

![change_margin](https://user-images.githubusercontent.com/36689800/81950024-20a9e300-960c-11ea-935c-ff3a322cf3ab.PNG)

**Comment by robertgr991** [comment]
@muametgrooby I just published a new version with configuration settings for the vertical and horizontal padding. Also, for the opacity, you can actually use the #RRGGBBAA notation for the text and background color, something like this:

![decoration_opacity](https://user-images.githubusercontent.com/36689800/82091661-6e077c80-9700-11ea-9017-40fd2a99f63f.PNG)

Let me know how this works and close the issue if everything is fine. Thx.

**Comment by muametgrooby** [comment]
> @muametgrooby I just published a new version with configuration settings for the vertical and horizontal padding. Also, for the opacity, you can actually use the #RRGGBBAA notation for the text and background color, something like this:
> 
> ![decoration_opacity](https://user-images.githubusercontent.com/36689800/82091661-6e077c80-9700-11ea-9017-40fd2a99f63f.PNG)
> 
> Let me know how this works and close the issue if everything is fine. Thx.

Hello, apparently even if horizontal padding is at 0, theres still padding/spacing at the right and the left side, tried negative values didnt work.

![image](https://user-images.githubusercontent.com/42146933/82126756-f8a6b500-97ae-11ea-8589-6d0be5ceeb3b.png)

There seems to be a white space right after the colon, how do i get rid of that? If its possible. Great extension btw i love it!

**Comment by robertgr991** [comment]
Yes, you are right, there is a space both before and after the hint, with the new padding settings I may remove these white space characters so it is fully customizable, but right now it's not possible, I have to publish another version. Maybe tomorrow. 

You can try to decrease the space between the parentheses and the parameter as I've shown in my first comment, but it's not exactly what you want.

**Comment by robertgr991** [comment]
@muametgrooby

 I removed the white spaces in the last version, but I increased the default horizontal padding so the decorations look like before, now you can set the padding to 0 and there won't be any spaces left.

**Comment by muametgrooby** [comment]
Thank you, its perfect!
